import 'lifecycle_status.dart';
import 'water_point_access.dart';
import 'accessibility_info.dart';

/// Represents a physical water supply infrastructure asset registered in AguaCION.
///
/// CRITICAL ARCHITECTURAL PRINCIPLE:
/// [WaterPoint] encapsulates purely RELATIVELY STATIC infrastructure identity and characteristics.
/// It NEVER contains volatile, real-time emergency operational states such as:
/// - current queue length or wait time;
/// - whether water is currently flowing or available;
/// - temporary emergency closures;
/// - last operational ping timestamp.
///
/// Those dynamic observations belong strictly inside [WaterPointStatus].
class WaterPoint {
  /// Canonical, persistent unique identifier generated by AguaCION
  /// (e.g. `WP-SED-SUR-3B91385998-SAN ISIDRO`).
  final String waterPointId;

  /// Cryptographic or algorithmic fingerprint of the raw source attributes
  /// when this record was ingested, enabling detection of source-level modifications.
  final String? sourceRecordFingerprint;

  /// Official asset identifier or code in the enterprise GIS of the utility (SEDAPAL/SUNASS),
  /// if provided. (e.g. `R-P1`, or null if not assigned).
  final String? officialCode;

  /// Official name or reference of the point (e.g. `Ca. Los Cedros Cdra. 03 (Parque Dammert)`).
  final String name;

  /// Raw component or facility classification as received from source (e.g. `CÁMARA CON MANIFOLD`, `POZO`, `RESERVORIO`).
  final String componentTypeRaw;

  /// Exact geographic coordinates of the physical hydraulic asset.
  final GeoLocation infrastructureLocation;

  /// Verified physical pedestrian entry coordinate where citizens line up, if known.
  /// Null if unverified or if identical to infrastructure location.
  final GeoLocation? pedestrianAccessLocation;

  /// Administrative department name (e.g. `LIMA`).
  final String department;

  /// Administrative province name (e.g. `LIMA` or `CALLAO`).
  final String province;

  /// Administrative district name (e.g. `SAN ISIDRO`, `SANTIAGO DE SURCO`).
  /// NOTE: District is strictly geographic metadata, NEVER an automatic operational boundary or hard filter!
  final String district;

  /// Official 6-digit UBIGEO code from INEI (e.g. `150131`).
  final String? districtUbigeo;

  /// Equipment Operation and Network Maintenance zone (e.g. `EOMR-SUR`, `EOMR-SJL`).
  final String? eomr;

  /// Raw capacity string as stated in official documents (e.g. `"15.00"`, `"2.00"`).
  /// Under ZERO circumstances is a unit of measure (L/s, m3/h, m3) invented or appended.
  final String? capacityRaw;

  /// Raw situation string as reported by the utility (e.g. `"Operativo"`, `"En implementación"`).
  final String? situationRaw;

  /// Raw state string as reported by the utility (e.g. `"Activo"`, `"En reserva"`).
  final String? stateRaw;

  /// Raw power generator indicator as stated in official records (e.g. `"Sí"`, `"No"`, `"No corresponde"`).
  final String? generatorRaw;

  /// Source provenance of this infrastructure record (e.g. `"SUNASS_SEDAPAL_OFFICIAL_20260819"`).
  final String source;

  /// Publication or cutoff date of the source dataset.
  final DateTime? datasetSourceDate;

  /// Timestamp when this infrastructure record was first recognized by AguaCION.
  final DateTime? firstSeenInSourceAt;

  /// Administrative effective date of this infrastructure definition.
  final DateTime? validFrom;

  /// Lifecycle status of the asset (active, pending review, missing from latest delivery, retired).
  final LifecycleStatus lifecycleStatus;

  /// Optional formal service area identifier, if defined institutionally by authorities.
  /// Null by default.
  final String? serviceAreaId;

  /// Physical accessibility details (wheelchair, stairs, slope), nullable.
  final AccessibilityInfo? accessibilityInfo;

  const WaterPoint({
    required this.waterPointId,
    this.sourceRecordFingerprint,
    this.officialCode,
    required this.name,
    required this.componentTypeRaw,
    required this.infrastructureLocation,
    this.pedestrianAccessLocation,
    required this.department,
    required this.province,
    required this.district,
    this.districtUbigeo,
    this.eomr,
    this.capacityRaw,
    this.situationRaw,
    this.stateRaw,
    this.generatorRaw,
    required this.source,
    this.datasetSourceDate,
    this.firstSeenInSourceAt,
    this.validFrom,
    this.lifecycleStatus = LifecycleStatus.active,
    this.serviceAreaId,
    this.accessibilityInfo,
  });

  /// Coordinate used strictly for map rendering and spatial display.
  GeoLocation get displayLocation => infrastructureLocation;

  /// Verified physical pedestrian access location.
  /// Null if unverified on-site: under zero circumstances is a coordinate invented!
  GeoLocation? get routingAccessLocation => pedestrianAccessLocation;

  /// True ONLY if an on-site verified pedestrian access point exists.
  bool get isPedestrianAccessVerified => pedestrianAccessLocation != null;

  /// Provisional routing target for POC technical graph routing.
  ///
  /// CRITICAL ARCHITECTURAL DISTINCTION (Hito 3A Corrective Closure):
  /// Labeled explicitly: PROVISIONAL_TECHNICAL_ROUTING_TARGET.
  /// When [pedestrianAccessLocation] is null, falls back to [infrastructureLocation]
  /// to enable technical graph traversal in the POC engine. This does NOT represent
  /// or imply a validated citizen pedestrian access point.
  GeoLocation get provisionalTechnicalRoutingTarget =>
      pedestrianAccessLocation ?? infrastructureLocation;

  /// Backwards-compatible alias targeting [provisionalTechnicalRoutingTarget].
  GeoLocation get effectiveLocation => provisionalTechnicalRoutingTarget;

  /// True if a dedicated pedestrian access point has been verified.
  bool get hasDedicatedPedestrianAccess => pedestrianAccessLocation != null;

  WaterPoint copyWith({
    String? waterPointId,
    String? sourceRecordFingerprint,
    String? officialCode,
    String? name,
    String? componentTypeRaw,
    GeoLocation? infrastructureLocation,
    GeoLocation? pedestrianAccessLocation,
    String? department,
    String? province,
    String? district,
    String? districtUbigeo,
    String? eomr,
    String? capacityRaw,
    String? situationRaw,
    String? stateRaw,
    String? generatorRaw,
    String? source,
    DateTime? datasetSourceDate,
    DateTime? firstSeenInSourceAt,
    DateTime? validFrom,
    LifecycleStatus? lifecycleStatus,
    String? serviceAreaId,
    AccessibilityInfo? accessibilityInfo,
  }) {
    return WaterPoint(
      waterPointId: waterPointId ?? this.waterPointId,
      sourceRecordFingerprint:
          sourceRecordFingerprint ?? this.sourceRecordFingerprint,
      officialCode: officialCode ?? this.officialCode,
      name: name ?? this.name,
      componentTypeRaw: componentTypeRaw ?? this.componentTypeRaw,
      infrastructureLocation:
          infrastructureLocation ?? this.infrastructureLocation,
      pedestrianAccessLocation:
          pedestrianAccessLocation ?? this.pedestrianAccessLocation,
      department: department ?? this.department,
      province: province ?? this.province,
      district: district ?? this.district,
      districtUbigeo: districtUbigeo ?? this.districtUbigeo,
      eomr: eomr ?? this.eomr,
      capacityRaw: capacityRaw ?? this.capacityRaw,
      situationRaw: situationRaw ?? this.situationRaw,
      stateRaw: stateRaw ?? this.stateRaw,
      generatorRaw: generatorRaw ?? this.generatorRaw,
      source: source ?? this.source,
      datasetSourceDate: datasetSourceDate ?? this.datasetSourceDate,
      firstSeenInSourceAt: firstSeenInSourceAt ?? this.firstSeenInSourceAt,
      validFrom: validFrom ?? this.validFrom,
      lifecycleStatus: lifecycleStatus ?? this.lifecycleStatus,
      serviceAreaId: serviceAreaId ?? this.serviceAreaId,
      accessibilityInfo: accessibilityInfo ?? this.accessibilityInfo,
    );
  }

  Map<String, dynamic> toJson() => {
    'waterPointId': waterPointId,
    if (sourceRecordFingerprint != null)
      'sourceRecordFingerprint': sourceRecordFingerprint,
    if (officialCode != null) 'officialCode': officialCode,
    'name': name,
    'componentTypeRaw': componentTypeRaw,
    'infrastructureLocation': infrastructureLocation.toJson(),
    if (pedestrianAccessLocation != null)
      'pedestrianAccessLocation': pedestrianAccessLocation!.toJson(),
    'department': department,
    'province': province,
    'district': district,
    if (districtUbigeo != null) 'districtUbigeo': districtUbigeo,
    if (eomr != null) 'eomr': eomr,
    if (capacityRaw != null) 'capacityRaw': capacityRaw,
    if (situationRaw != null) 'situationRaw': situationRaw,
    if (stateRaw != null) 'stateRaw': stateRaw,
    if (generatorRaw != null) 'generatorRaw': generatorRaw,
    'source': source,
    if (datasetSourceDate != null)
      'datasetSourceDate': datasetSourceDate!.toIso8601String(),
    if (firstSeenInSourceAt != null)
      'firstSeenInSourceAt': firstSeenInSourceAt!.toIso8601String(),
    if (validFrom != null) 'validFrom': validFrom!.toIso8601String(),
    'lifecycleStatus': lifecycleStatus.name,
    if (serviceAreaId != null) 'serviceAreaId': serviceAreaId,
    if (accessibilityInfo != null)
      'accessibilityInfo': accessibilityInfo!.toJson(),
  };

  factory WaterPoint.fromJson(Map<String, dynamic> json) {
    return WaterPoint(
      waterPointId: json['waterPointId'] as String,
      sourceRecordFingerprint: json['sourceRecordFingerprint'] as String?,
      officialCode: json['officialCode'] as String?,
      name: json['name'] as String,
      componentTypeRaw: json['componentTypeRaw'] as String? ?? 'PUNTO_FIJO',
      infrastructureLocation: GeoLocation.fromJson(
        json['infrastructureLocation'] as Map<String, dynamic>,
      ),
      pedestrianAccessLocation: json['pedestrianAccessLocation'] != null
          ? GeoLocation.fromJson(
              json['pedestrianAccessLocation'] as Map<String, dynamic>,
            )
          : null,
      department: json['department'] as String? ?? 'LIMA',
      province: json['province'] as String? ?? 'LIMA',
      district: json['district'] as String? ?? '',
      districtUbigeo: json['districtUbigeo'] as String?,
      eomr: json['eomr'] as String?,
      capacityRaw: json['capacityRaw']?.toString(),
      situationRaw: json['situationRaw'] as String?,
      stateRaw: json['stateRaw'] as String?,
      generatorRaw: json['generatorRaw'] as String?,
      source: json['source'] as String? ?? 'UNKNOWN_SOURCE',
      datasetSourceDate: json['datasetSourceDate'] != null
          ? DateTime.parse(json['datasetSourceDate'] as String)
          : null,
      firstSeenInSourceAt: json['firstSeenInSourceAt'] != null
          ? DateTime.parse(json['firstSeenInSourceAt'] as String)
          : null,
      validFrom: json['validFrom'] != null
          ? DateTime.parse(json['validFrom'] as String)
          : null,
      lifecycleStatus: LifecycleStatus.fromString(
        json['lifecycleStatus'] as String?,
      ),
      serviceAreaId: json['serviceAreaId'] as String?,
      accessibilityInfo: json['accessibilityInfo'] != null
          ? AccessibilityInfo.fromJson(
              json['accessibilityInfo'] as Map<String, dynamic>,
            )
          : null,
    );
  }
}
